on:
  push:
    branches: [master]
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: calculate version
        id: calculate-version
        uses: bitshifted/git-auto-semver@v1
        with:
          main_branch: master
          create_tag: true
          initial_version: 1.0.0
          tag_prefix: 'deployment'

      - name: Use version
        run: echo "Calculated version ${{ steps.calculate-version.outputs.version-string }}"