on:
  push:
    branches: [master]

name: Generate Sementic Versioning and Create Tag
jobs:
  build:
    permissions: write-all
    name: Generate Sementic Versioning and Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: check git from outside
        run: git describe --tags `git rev-list --tags --max-count=1`
      
      - name: Get Previous Version
        id: get-previous-version
        run: bash ./05-generate-semver-and-create-tag/previous-version.sh

      - name: Check the previous version generated
        run: |
          echo "The next version is ${{ steps.get-previous-version.outputs.PREVIOUS_VERSION }}"

      - name: Generate Next Version
        id: generate-next-version
        run: bash ./05-generate-semver-and-create-tag/next-version.sh -m ${{steps.get-previous-version.outputs.PREVIOUS_VERSION}}

      - name: Check the version generated
        run: |
          echo "The next version is ${{ steps.generate-next-version.outputs.NEXT_VERSION }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{steps.generate-next-version.outputs.NEXT_VERSION}}
          release_name: Release ${{ steps.generate-next-version.outputs.NEXT_VERSION }}
          draft: false
          prerelease: false
